// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	BookID      int32              `json:"book_id"`
	Name        string             `json:"name"`
	PublishDate string             `json:"publish_date"`
	Price       int32              `json:"price"`
	Sku         string             `json:"sku"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	CustomerID  int32  `json:"customer_id"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	City        string `json:"city"`
	PhoneNumber string `json:"phone_number"`
}

type CustomerOrder struct {
	CustomerOrderID  int32  `json:"customer_order_id"`
	OrderDate        string `json:"order_date"`
	CustomerID       int32  `json:"customer_id"`
	ShippingMethodID int32  `json:"shipping_method_id"`
}

type OrderLine struct {
	LineID  int32 `json:"line_id"`
	OrderID int32 `json:"order_id"`
	BookID  int32 `json:"book_id"`
	Price   int32 `json:"price"`
}

type ShippingMethod struct {
	ShippingMethodID int32  `json:"shipping_method_id"`
	Name             string `json:"name"`
	Cost             int32  `json:"cost"`
}
